/* Curry District · Festivals & Promotions Calendar — shared data (page + asset renderer).
   Rules: no prices, discounts, offers, scarcity, halal/vegan/GF or "authentic" claims.
   Dates: fixed civic dates are exact; Diwali (Nov 8, 2026), Dussehra (~Oct 20, 2026) and Thanksgiving (Nov 26, 2026)
   come from research/social_gbp_playbook.md; every lunisolar/lunar date is month-level and flagged approx. */
(function (root) {
  var APPROX = 'approx — lunisolar dates vary; verify yearly';
  var LUNAR = 'approx — set by moon sighting; verify the week before';

  var MONTHS = [
    { key: '2026-10', short: 'Oct', name: 'October', year: 2026, g: 'linear-gradient(150deg,#FFB000,#FF6A13 60%,#E4147E)', ry: 'linear-gradient(150deg,#A3173F,#4B1D52)', season: 'Festival season opens' },
    { key: '2026-11', short: 'Nov', name: 'November', year: 2026, g: 'linear-gradient(150deg,#1D1147,#3A1B7A 55%,#E4147E 130%)', ry: 'linear-gradient(150deg,#160B26,#4B1D52)', season: 'Lights & a long table' },
    { key: '2026-12', short: 'Dec', name: 'December', year: 2026, g: 'linear-gradient(150deg,#00A8A0,#3FA34D)', ry: 'linear-gradient(150deg,#0F4D3F,#117C86)', season: 'Party-tray season' },
    { key: '2027-01', short: 'Jan', name: 'January', year: 2027, g: 'linear-gradient(150deg,#FFE7B8,#FFB000)', ry: 'linear-gradient(150deg,#117C86,#0F4D3F)', season: 'Kites & harvest' },
    { key: '2027-02', short: 'Feb', name: 'February', year: 2027, g: 'linear-gradient(150deg,#E4147E,#D62839)', ry: 'linear-gradient(150deg,#A3173F,#160B26)', season: 'Game night & date night' },
    { key: '2027-03', short: 'Mar', name: 'March', year: 2027, g: 'linear-gradient(150deg,#7B5CFF,#E4147E 55%,#FFB000)', ry: 'linear-gradient(150deg,#4B1D52,#0F4D3F)', season: 'Color & warm wishes' },
    { key: '2027-04', short: 'Apr', name: 'April', year: 2027, g: 'linear-gradient(150deg,#3FA34D,#00A8A0)', ry: 'linear-gradient(150deg,#0F4D3F,#160B26)', season: 'New year, new heat' },
    { key: '2027-05', short: 'May', name: 'May', year: 2027, g: 'linear-gradient(150deg,#FF6A13,#E4147E)', ry: 'linear-gradient(150deg,#F4C9BB,#A3173F)', season: 'Family tables' },
    { key: '2027-06', short: 'Jun', name: 'June', year: 2027, g: 'linear-gradient(150deg,#FFB000,#3FA34D)', ry: 'linear-gradient(150deg,#117C86,#4B1D52)', season: 'Grads & dads' },
    { key: '2027-07', short: 'Jul', name: 'July', year: 2027, g: 'linear-gradient(150deg,#00A8A0,#3A1B7A)', ry: 'linear-gradient(150deg,#160B26,#117C86)', season: 'Lake days' },
    { key: '2027-08', short: 'Aug', name: 'August', year: 2027, g: 'linear-gradient(150deg,#FF6A13,#FFB000)', ry: 'linear-gradient(150deg,#4B1D52,#A3173F)', season: 'Back to routine' },
    { key: '2027-09', short: 'Sep', name: 'September', year: 2027, g: 'linear-gradient(150deg,#D62839,#1D1147)', ry: 'linear-gradient(150deg,#160B26,#0F4D3F)', season: 'Friday nights' }
  ];

  /* cat: indian | us   ·   catering: true when the money is in trays/platters   ·   approx: show the approx flag
     dateKind: research (date given in /research) | fixed (civic date) | month (month-level only)
     ics: start (YYYY-MM-DD, all-day), marker (true = month-level planning marker on the 1st), rrule, alarm (days before) */
  var MOMENTS = [
    {
      id: 'navratri-dussehra', month: '2026-10', name: 'Navratri & Dussehra season', short: 'Navratri & Dussehra',
      cat: 'indian', catering: true, approx: true, dateKind: 'research',
      dateLabel: 'October 2026 · Dussehra ~Oct 20', dateShort: '~Oct 20', dateNote: APPROX + '. Oct 20 comes from our 30-day plan (Day 9).',
      ics: { start: '2026-10-20', alarm: 10 }, icon: 'garland', post: 'navratri-dussehra', kit: 'topper',
      about: 'A nine-night festival season that ends with Dussehra; many families gather, dance and share food.',
      concept: 'Garlands up, plates full: a warm Dussehra greeting, plus easy vegetarian snack trays for garba-night hosts.',
      lead: 'Greeting on the day; trays pitched from Oct 12',
      channels: {
        ig: { action: 'Greeting post on Dussehra day: marigold torans and the Paneer Tikka plate.',
          bz: 'Happy Dussehra, Little Elm! Garlands up, plates full. Warm wishes from all of us on FM 423. #Dussehra #LittleElm #DFWFoodie',
          ry: 'Happy Dussehra. Marigolds at the door, a generous table inside. Warm wishes from all of us at Curry District. #Dussehra #LittleElmTX' },
        story: { action: '3 frames: torans going up, kitchen B-roll, then a “Hosting garba night?” poll.',
          bz: 'Garba night at yours? Tap if the crew needs snacks.',
          ry: 'Hosting friends after the dancing? Ask us about trays for your group.' },
        gbp: { action: 'Update post with a Call button, pointing to catering.',
          bz: 'Hosting a garba night or a Dussehra get-together in Little Elm? Vegetarian picks like Paneer Tikka and Veg Samosa travel well. Call Curry District to plan.',
          ry: 'Celebrating Dussehra with family and friends? Call Curry District in Little Elm to plan vegetarian and non-vegetarian trays for your gathering.' },
        store: { action: 'Festival bag topper on catering orders; marigold counter card.',
          bz: 'Happy Dussehra! Garlands up, plates full.',
          ry: 'With warm Dussehra wishes.' }
      },
      kpi: 'Catering calls that mention Dussehra or garba, plus saves on the greeting post.',
      notes: ['Greeting only: no deity imagery, no religious storytelling.', 'Navratri and Dussehra move every year. Verify before scheduling.']
    },
    {
      id: 'diwali', month: '2026-11', name: 'Diwali', short: 'Diwali',
      cat: 'indian', catering: true, approx: true, dateKind: 'research',
      dateLabel: 'Sun Nov 8, 2026', dateShort: 'Nov 8', dateNote: APPROX + '. Nov 8 is the research date, still marked “verify”.',
      ics: { start: '2026-11-08', alarm: 21 }, icon: 'lights', post: 'diwali', kit: 'sticker-lights',
      about: 'The festival of lights: homes glow with lamps and string lights, and families share sweets and big meals.',
      concept: 'You do the lights, we’ll do the feast: a 3-week pre-order push for family platters, ending in a greeting on the day.',
      lead: 'Start posting Oct 19 (3 weeks out)',
      channels: {
        ig: { action: 'Carousel 3 weeks out (family spread), then the greeting post on the day.',
          bz: 'Lights on, sweets out. Hosting Diwali? Let us handle the platters while you handle the lights. Call us to plan. ✨ #Diwali2026 #DFWDiwali #LittleElm',
          ry: 'Lights up, plates full, everyone home. Planning a Diwali gathering? Call us to plan your catering. #Diwali2026 #LittleElmTX' },
        story: { action: 'Countdown sticker and “lights going up” setup clips (Day 24 of the 30-day plan).',
          bz: 'Lights going up on FM 423. Countdown’s on!',
          ry: 'The dining room is glowing. Counting down to Diwali.' },
        gbp: { action: 'Event post, plus Special hours set a month ahead.',
          bz: 'Diwali at Curry District, Little Elm! Order ahead for the family feast: biryani, Butter Chicken, garlic naan and more. Call us to plan.',
          ry: 'Celebrate Diwali around a generous table. Curry District in Little Elm caters family gatherings; call ahead to plan your order.' },
        store: { action: '“Festival of Lights” sticker on every bag for 3 weeks; bag topper on catering orders.',
          bz: 'Happy Diwali from the District!',
          ry: 'Wishing you a bright Diwali.' }
      },
      kpi: 'Pre-order and catering calls Oct 19 to Nov 8 against a normal 3-week window, plus GBP direction requests that week.',
      notes: ['Generic string lights, marigolds and rangoli-style geometry only. No deity imagery.', 'Confirm Gulab Jamun is on the current menu before featuring it.', 'Set GBP special hours a month ahead.']
    },
    {
      id: 'thanksgiving', month: '2026-11', name: 'Thanksgiving & Friendsgiving', short: 'Thanksgiving',
      cat: 'us', catering: true, approx: false, dateKind: 'fixed',
      dateLabel: 'Thu Nov 26, 2026', dateShort: 'Nov 26', dateNote: 'Fixed date (4th Thursday). Friendsgivings run all month.',
      ics: { start: '2026-11-26', alarm: 14 }, icon: 'leaf', post: 'thanksgiving', kit: 'sticker-feast',
      about: 'The big US family-table holiday; Friendsgiving potlucks fill the weekends around it.',
      concept: 'Pass the naan: Friendsgiving and Thanksgiving trays that make any table a little louder.',
      lead: 'Trays pitched from Nov 9',
      channels: {
        ig: { action: 'Reel of the tandoori platter, then a “what to bring” carousel.',
          bz: 'Pass the naan, not the stress. Friendsgiving trays from the Tandoor Quarter. Call us to plan. #Friendsgiving #LittleElm #DFWEats',
          ry: 'Gratefully shared. Thanksgiving catering from Curry District, planned with you. #Thanksgiving #LittleElmTX' },
        story: { action: 'Poll: “Turkey or Tandoori Chicken?” with a link sticker to catering.',
          bz: 'Turkey or Tandoori Chicken? Vote, then call us.',
          ry: 'This year, add something new to the table. Tap to plan.' },
        gbp: { action: 'Update post, plus Special hours for Nov 26.',
          bz: 'Thanksgiving and Friendsgiving trays from Curry District in Little Elm: tandoori, biryani, curries and garlic naan. Call us to plan.',
          ry: 'Hosting Thanksgiving? Curry District in Little Elm can cater the table. Check our holiday hours and call ahead to plan.' },
        store: { action: '“Feast Season” sticker on catering bags; table tent: “Ask about Friendsgiving trays”.',
          bz: 'Feast season starts here.',
          ry: 'Grateful for good company.' }
      },
      kpi: 'Catering orders Nov 16 to 26, plus taps on the Friendsgiving poll.',
      notes: ['Holiday hours are unverified. Confirm them before posting.', 'No prices or bundles in posts.']
    },
    {
      id: 'holiday-trays', month: '2026-12', name: 'Holiday & New Year’s Eve party trays', short: 'Holiday & NYE trays',
      cat: 'us', catering: true, approx: false, dateKind: 'fixed',
      dateLabel: 'Dec 25 & Dec 31, 2026', dateShort: 'Dec 25 · 31', dateNote: 'Fixed dates. Office parties run the first three weeks of December.',
      ics: { start: '2026-12-31', alarm: 25 }, icon: 'gift', post: 'holiday-trays', kit: 'sticker-feast',
      about: 'Office parties, family visits and New Year’s Eve make this the busiest hosting month of the year.',
      concept: 'Party trays, sorted: office-party and NYE trays with one phone call, pushed from the first week of December.',
      lead: 'Push from Dec 1; NYE reminder Dec 26',
      channels: {
        ig: { action: 'Carousel: “Build your party table” (starters, mains, naan, something sweet).',
          bz: 'Office party? NYE crew? Bring the guest list and we’ll handle the trays. 🎉 #HolidayParty #DFWCatering #LittleElm',
          ry: 'Hosting, made gracious. Holiday and New Year’s Eve trays from Curry District. Call to plan. #DFWCatering #LittleElmTX' },
        story: { action: 'NYE countdown plus an “Office party?” question box.',
          bz: 'How big is your crew? Drop the number.',
          ry: 'Tell us about your gathering and we’ll take it from there.' },
        gbp: { action: 'Update post with a Call button, plus Special hours for Dec 24–25, Dec 31 and Jan 1.',
          bz: 'Holiday parties and New Year’s Eve, catered from Little Elm: biryani trays, tandoori, curries and naan for the whole crowd. Call Curry District to plan.',
          ry: 'Curry District in Little Elm caters holiday and New Year’s Eve gatherings. Call ahead to plan your trays, and check our holiday hours.' },
        store: { action: '“Feast Season” sticker continues; bag topper on catering orders.',
          bz: 'Feast season. Pass it on.',
          ry: 'Season’s greetings from Curry District.' }
      },
      kpi: 'Catering enquiries Dec 1 to 31, and corporate orders from Frisco and Legacy (tag the source).',
      notes: ['Keep it secular: ribbons, lights and confetti, no religious imagery.', 'Holiday hours are unverified.']
    },
    {
      id: 'sankranti-pongal', month: '2027-01', name: 'Makar Sankranti & Pongal', short: 'Sankranti & Pongal',
      cat: 'indian', catering: false, approx: true, dateKind: 'month',
      dateLabel: 'Mid-January 2027', dateShort: 'mid-Jan', dateNote: APPROX + '.',
      ics: { start: '2027-01-01', marker: true, alarm: 0 }, icon: 'kite', post: 'sankranti-pongal', kit: null,
      about: 'Mid-January harvest festivals: kite flying for many Sankranti households, and Pongal for Tamil families.',
      concept: 'Kites up, chai out: a bright harvest-season greeting, plus a weekend chai-and-snacks moment.',
      lead: 'Greeting on the day; weekend story push',
      channels: {
        ig: { action: 'Greeting post: kites over the chai and lassi art.',
          bz: 'Kites up, chai out. Happy Sankranti and Pongal, Little Elm! #Sankranti #Pongal #LittleElm',
          ry: 'A harvest of wishes: happy Makar Sankranti and Pongal from our kitchen to your home. #Sankranti #Pongal' },
        story: { action: 'Kite stickers and a “Chai lo” frame.',
          bz: 'Chai lo (have some chai). Kite-watching optional.',
          ry: 'Warm chai for a cool January afternoon.' },
        gbp: { action: 'Update post with a chai-and-snacks photo.',
          bz: 'Celebrating Sankranti or Pongal? Warm up with chai, samosas and the whole District menu in Little Elm. Order pickup or dine in.',
          ry: 'Harvest-season wishes from Curry District in Little Elm. Join us for chai and a generous table this weekend.' },
        store: { action: 'Kite counter card; no bag sticker needed.',
          bz: 'Happy Sankranti! Happy Pongal!',
          ry: 'Happy Sankranti & Pongal.' }
      },
      kpi: 'Weekend pickup orders against the weekend before, plus story replies.',
      notes: ['Sankranti is one of the biggest family festivals in Andhra Pradesh and Telangana. A Telugu greeting would land well, with native-speaker sign-off.', 'Usually mid-January, but verify the date each year.']
    },
    {
      id: 'big-game', month: '2027-02', name: 'Big-game Sunday', short: 'Big-game Sunday',
      cat: 'us', catering: true, approx: true, dateKind: 'month',
      dateLabel: 'Early–mid February 2027', dateShort: 'early Feb', dateNote: 'Verify the NFL schedule. Month-level only.',
      ics: { start: '2027-02-01', marker: true, alarm: 0 }, icon: 'ball', post: null, kit: 'sticker-game',
      about: 'America’s biggest football watch-party day.',
      concept: 'Snacks that score: game-day trays of Chicken 65, Chilli Chicken and samosas in place of the usual wings.',
      lead: 'Pre-orders open 10 days out',
      channels: {
        ig: { action: 'Reel: a tray build-up cut to a whistle sound.',
          bz: 'Snacks that score. Watch-party trays from Indo-Chinese Alley. Call us to plan. 🏈 #GameDay #LittleElm #DFWEats',
          ry: 'The watch party, elevated. Order trays ahead for the big game. #GameDay #LittleElmTX' },
        story: { action: '“Which snack wins?” bracket poll.',
          bz: 'Chilli Chicken vs Gobi Manchurian. Pick your winner.',
          ry: 'Which starter would you put on the table?' },
        gbp: { action: 'Update post a week before, with an Order online button.',
          bz: 'Hosting the big game? Pre-order Chicken 65, Chilli Chicken and Veg Samosa trays from Curry District in Little Elm. Order online or call.',
          ry: 'Planning a watch party? Curry District in Little Elm prepares trays for groups. Order ahead so kickoff stays relaxed.' },
        store: { action: '“Game Day” sticker on orders Friday to Sunday of game weekend.',
          bz: 'Game day, District style.',
          ry: 'Game day, well fed.' }
      },
      kpi: 'Online orders on game weekend against a normal weekend, plus tray pre-orders.',
      notes: ['Say “the big game”. The official game name and team logos are trademarks; keep them out of posts and ads.']
    },
    {
      id: 'valentines', month: '2027-02', name: 'Valentine’s date night', short: 'Valentine’s',
      cat: 'us', catering: false, approx: false, dateKind: 'fixed',
      dateLabel: 'Sun Feb 14, 2027', dateShort: 'Feb 14', dateNote: 'Fixed date. Galentine’s tables run the days before.',
      ics: { start: '2027-02-14', alarm: 10 }, icon: 'heart', post: 'valentines', kit: null,
      about: 'Date-night dinners and Galentine’s get-togethers.',
      concept: 'Dinner, made an occasion: a Royal-led date-night push with a shareable “two plates, one garlic naan” line.',
      lead: 'Post Feb 4 and Feb 12',
      channels: {
        ig: { action: 'Butter Chicken hero post (the Royal look shines here).',
          bz: 'Love at first dip. Two plates, one shared garlic naan. ❤️ #DateNightDFW #LittleElm',
          ry: 'Dinner, made an occasion. Two plates, one shared garlic naan and nowhere else to be. #DateNightDFW #LittleElmTX' },
        story: { action: 'This-or-that date-night picks, plus a Galentine’s group-table question.',
          bz: 'Butter Chicken or Tikka Masala? Choose wisely, it’s a date.',
          ry: 'Plan your evening: dine in, or bring the candlelight home with pickup.' },
        gbp: { action: 'Update post with a Call button for larger Galentine’s groups.',
          bz: 'Date night in Little Elm: Butter Chicken, Chicken Tikka Masala and garlic naan, made for sharing at Curry District. Dine in or order pickup.',
          ry: 'Make Valentine’s an occasion at Curry District in Little Elm: generous plates and a warm welcome. Call ahead for larger groups.' },
        store: { action: 'Small paisley-heart sticker on pickup bags Feb 12 to 15.',
          bz: 'Made with love (and garlic).',
          ry: 'Shared with love.' }
      },
      kpi: 'Dine-in covers Feb 12 to 15, plus saves and shares on the post.',
      notes: ['Don’t promise reservations unless the restaurant takes them (counter service is likely).']
    },
    {
      id: 'eid', month: '2027-03', name: 'Eid al-Fitr', short: 'Eid al-Fitr',
      cat: 'indian', catering: false, approx: true, dateKind: 'month',
      dateLabel: 'Around March 2027', dateShort: '~Mar', dateNote: LUNAR + '.',
      ics: { start: '2027-03-01', marker: true, alarm: 0 }, icon: 'star8', post: 'eid', kit: null,
      about: 'A major celebration for Muslim families, marking the end of Ramadan.',
      concept: 'A quiet, text-led Eid greeting on geometric pattern: warm wishes, no hard sell.',
      lead: 'Greeting on the day only',
      channels: {
        ig: { action: 'Text-led greeting on star-tile geometry. No food push on the day.',
          bz: 'Eid Mubarak to everyone celebrating in Little Elm and beyond. Warm wishes from all of us at Curry District.',
          ry: 'Eid Mubarak. Warm wishes to you and your loved ones from all of us at Curry District.' },
        story: { action: 'One greeting frame, with no sales stickers.',
          bz: 'Eid Mubarak, Little Elm!',
          ry: 'Eid Mubarak, from all of us.' },
        gbp: { action: 'Optional Update post; set special hours only if they change.',
          bz: 'Eid Mubarak from Curry District in Little Elm! Planning a get-together? Call us. We’re happy to answer menu questions directly.',
          ry: 'Eid Mubarak from all of us at Curry District, Little Elm. For gatherings, please call. We’re happy to answer menu questions directly.' },
        store: { action: 'Greeting card at the counter. Keep packaging unchanged.',
          bz: 'Eid Mubarak!',
          ry: 'Eid Mubarak.' }
      },
      kpi: 'Reach, plus positive replies and shares from local community accounts.',
      notes: ['Have community members review the wording and imagery before publishing.', 'Don’t imply halal status. It’s unverified, so answer menu questions by phone.', 'Eid al-Adha follows about ten weeks later (around May 2027). Use the same text-led approach.']
    },
    {
      id: 'holi', month: '2027-03', name: 'Holi', short: 'Holi',
      cat: 'indian', catering: false, approx: true, dateKind: 'month',
      dateLabel: 'March 2027', dateShort: 'Mar', dateNote: APPROX + '.',
      ics: { start: '2027-03-01', marker: true, alarm: 0 }, icon: 'burst', post: 'holi', kit: 'sticker-color',
      about: 'The spring festival of colors: friends and families celebrate outdoors with bright powders and sweets.',
      concept: 'Color me hungry: a bright reel and post with snacks for the after-party, plus a color-burst bag sticker.',
      lead: 'Post 1 week out and on the day',
      channels: {
        ig: { action: 'Reel: a color burst that transitions into the samosa plate.',
          bz: 'Color me hungry. Happy Holi, Little Elm! After-party snacks are on FM 423. 🎨 #Holi #DFWHoli #LittleElm',
          ry: 'Happy Holi. Bright colors outside, bright flavors at the table. #Holi #LittleElmTX' },
        story: { action: 'Color poll: “Which color are you?”, with each color mapped to a dish.',
          bz: 'Pink, green or saffron? Every color gets a snack.',
          ry: 'Choose your color and we’ll suggest a dish.' },
        gbp: { action: 'Update post with a photo and an Order online button.',
          bz: 'Happy Holi from Curry District! After the colors, refuel with Veg Samosa, Paneer Tikka and chai in Little Elm. Order pickup or dine in.',
          ry: 'Holi wishes from Curry District, Little Elm. Gather after the celebrations for chai and plates made for sharing.' },
        store: { action: '“Color Season” sticker on bags in Holi week.',
          bz: 'Holi hai! (It’s Holi!)',
          ry: 'Happy Holi.' }
      },
      kpi: 'Reel shares and UGC tags from Holi events, plus pickup orders that weekend.',
      notes: ['Colors and fun only: no deity imagery, no religious storytelling.', 'Community Holi events in Frisco and Plano could be a tray partnership. Verify the organizers.']
    },
    {
      id: 'ugadi', month: '2027-04', name: 'Ugadi (Telugu New Year)', short: 'Ugadi',
      cat: 'indian', catering: false, approx: true, dateKind: 'month',
      dateLabel: 'Late March – April 2027', dateShort: 'Mar/Apr', dateNote: APPROX + '.',
      ics: { start: '2027-04-01', marker: true, alarm: 0 }, icon: 'chili', post: 'ugadi', kit: null,
      about: 'New Year’s Day for Telugu and Kannada families, marked with fresh starts and a family meal.',
      concept: 'New year, new heat: spotlight the Andhra-leaning dishes for the Telugu families who know them best.',
      lead: 'Greeting on the day; Andhra carousel that week',
      channels: {
        ig: { action: 'Greeting post, plus an “Andhra side of the menu” carousel.',
          bz: 'New year, new heat. Happy Ugadi! Karampodi Chicken and Gongura Mutton Pulav are calling. #Ugadi #AndhraFood #LittleElm',
          ry: 'Happy Ugadi. A new year at the table, with Andhra-style fire and a little sweetness. #Ugadi #AndhraFood' },
        story: { action: '“How hot is your new year?” spice slider.',
          bz: 'Rate your new-year heat, from mild to full Andhra fire.',
          ry: 'Start the year bold. Tell us your spice level.' },
        gbp: { action: 'Update post featuring the Andhra-style dishes.',
          bz: 'Happy Ugadi from Little Elm! Celebrate with Andhra-style favorites at Curry District: Karampodi Chicken, Gongura Mutton Pulav and Andhra Goat Curry.',
          ry: 'Ugadi wishes from Curry District. Our Andhra-style dishes, from Gongura Mutton Pulav to Karampodi Chicken, are made for a festive table.' },
        store: { action: 'Counter card in English. Add a Telugu greeting only after native-speaker sign-off.',
          bz: 'Happy Ugadi! New year, new heat.',
          ry: 'Happy Ugadi.' }
      },
      kpi: 'Orders of the Andhra-style dishes in Ugadi week against an average week, plus shares from Telugu community groups.',
      notes: ['A Telugu greeting would land well. Have a native speaker (ideally the owners) write and sign it off.', 'Dish names come from public listings. Confirm them against the live menu.']
    },
    {
      id: 'cricket', month: '2027-04', name: 'Cricket season: spring T20 to summer MLC', short: 'Cricket season',
      cat: 'us', catering: true, approx: true, dateKind: 'month',
      dateLabel: 'Late March – July 2027', dateShort: 'Apr–Jul', dateNote: 'Verify the league schedules each year (research: “verify season”).',
      ics: { start: '2027-04-01', marker: true, alarm: 0 }, icon: 'bat', post: null, kit: 'sticker-game',
      about: 'Spring brings the big Indian T20 league to TV; summer brings Major League Cricket to Grand Prairie and weekend leagues to local parks.',
      concept: 'Match-night trays: watch-party orders for streaming nights, and “match-day trays” for local league teams.',
      lead: 'Weekly on big match nights',
      channels: {
        ig: { action: 'Reel: an over-by-over tray build. Post on big match nights.',
          bz: 'Six! That’s the sound of the biryani lid. Match-night trays, Little Elm. 🏏 #CricketNight #DFWCricket #LittleElm',
          ry: 'Match night, well hosted. Trays for your watch party, planned before the first ball. #DFWCricket #LittleElmTX' },
        story: { action: 'Prediction poll for big matches (no team logos).',
          bz: 'Who’s winning tonight? Loser fetches the naan.',
          ry: 'Watching tonight? Order ahead so you don’t miss an over.' },
        gbp: { action: 'Weekly Update post during the season, with an Order online button.',
          bz: 'Cricket night? Pre-order biryani, Chicken 65 and naan trays from Curry District in Little Elm for your watch party or league team.',
          ry: 'Curry District in Little Elm prepares trays for cricket watch parties and local league teams. Call or order online ahead of match time.' },
        store: { action: '“Game Day” sticker on match-night orders; flyer for local league captains.',
          bz: 'Game day, District style.',
          ry: 'Game day, well fed.' }
      },
      kpi: 'Orders on big match nights, plus the number of league teams ordering (track by team name).',
      notes: ['League names and team logos are trademarks. In posts, say “cricket season” and “match night”.']
    },
    {
      id: 'mothers-day', month: '2027-05', name: 'Mother’s Day', short: 'Mother’s Day',
      cat: 'us', catering: false, approx: false, dateKind: 'fixed',
      dateLabel: 'Sun May 9, 2027', dateShort: 'May 9', dateNote: 'Fixed date (2nd Sunday of May).',
      ics: { start: '2027-05-09', alarm: 10 }, icon: 'flower', post: 'mothers-day', kit: null,
      about: 'A big family dine-out and takeout day in the US.',
      concept: 'Mom’s night off: whole-family tables and pickup feasts, with a sweet finish.',
      lead: 'Post May 1 and May 8',
      channels: {
        ig: { action: 'Dal-and-saag comfort art with a “tag the mom who fed everyone” prompt.',
          bz: 'Mom’s night off. We’ll cook; you bring Mom. Tag the mom who fed everyone. #MothersDay #LittleElm #DFWEats',
          ry: 'Tonight, Mom is our guest. Mother’s Day at Curry District, Little Elm. #MothersDay #LittleElmTX' },
        story: { action: 'Question box: “Mom’s go-to order?”, then reshare the answers.',
          bz: 'What’s Mom’s order? Butter Chicken? Palak Paneer? Tell us.',
          ry: 'Share your mother’s favorite dish. We’d love to hear it.' },
        gbp: { action: 'Update post a week ahead; call ahead for big tables.',
          bz: 'Mother’s Day in Little Elm: bring the whole family to Curry District or order a pickup feast. Call ahead for big groups.',
          ry: 'Celebrate Mother’s Day around a generous table at Curry District, Little Elm. For larger family groups, please call ahead.' },
        store: { action: 'Marigold-and-jasmine sticker on pickup bags that weekend.',
          bz: 'For Mom, with extra naan.',
          ry: 'With love, for Mom.' }
      },
      kpi: 'Covers and pickup orders on May 8 and 9, plus tagged-mom comments.',
      notes: ['No “dessert for moms” style offers in this kit. Any offer needs owner sign-off.']
    },
    {
      id: 'grads-dads', month: '2027-06', name: 'Grad parties & Father’s Day', short: 'Grads & Father’s Day',
      cat: 'us', catering: true, approx: false, dateKind: 'fixed',
      dateLabel: 'June 2027 · Father’s Day Sun Jun 20', dateShort: 'Jun 20', dateNote: 'Father’s Day is fixed (3rd Sunday). Graduation dates: check the ISD calendars.',
      ics: { start: '2027-06-20', alarm: 21 }, icon: 'cap', post: null, kit: 'sticker-feast',
      about: 'High-school graduation parties and Father’s Day fill June weekends.',
      concept: 'Feed the whole crew: grad-party trays for Little Elm and Frisco families, plus a Father’s Day “Dad picks the heat” post.',
      lead: 'Grad trays from late May',
      channels: {
        ig: { action: 'Carousel: a grad-party tray guide, plus a Father’s Day spice-level post.',
          bz: 'Grad party? Bring the guest list; we’ll bring the biryani. Congrats, class of 2027! 🎓 #GradParty #LittleElm #DFWCatering',
          ry: 'Celebrate the graduate around a generous table. Catering for grad parties, planned with you. #GradParty #LittleElmTX' },
        story: { action: '“Tag a grad”, plus a Father’s Day “Dad’s heat level” slider.',
          bz: 'Dad picks the heat. How brave is he?',
          ry: 'This Father’s Day, let Dad choose the table.' },
        gbp: { action: 'Update post with a Call button for pickup trays.',
          bz: 'Grad parties and Father’s Day in Little Elm: Curry District caters trays of biryani, tandoori and curries. Call to plan.',
          ry: 'From graduation parties to Father’s Day dinners, Curry District in Little Elm caters gatherings of every size. Call to plan.' },
        store: { action: 'Reuse the “Feast Season” sticker; flyer at PTA events (research tie-in).',
          bz: 'Congrats, grads! Feast mode on.',
          ry: 'Congratulations, graduates.' }
      },
      kpi: 'Catering enquiries in June, plus PTA and school referrals.',
      notes: ['School names and logos are off-limits. Use generic caps and pennants.']
    },
    {
      id: 'july-4', month: '2027-07', name: 'Fourth of July lake day', short: 'July 4th',
      cat: 'us', catering: true, approx: false, dateKind: 'fixed',
      dateLabel: 'Sun Jul 4, 2027', dateShort: 'Jul 4', dateNote: 'Fixed date.',
      ics: { start: '2027-07-04', alarm: 10 }, icon: 'firework', post: 'july-4', kit: 'sticker-feast',
      about: 'Fireworks, lake days and backyard parties; the Little Elm lakefront gets busy.',
      concept: 'Lake day, naan night: pickup trays for the lake crowd, plus a fireworks-meets-rangoli post.',
      lead: 'Post Jun 28 and Jul 3',
      channels: {
        ig: { action: 'Fireworks drawn as rangoli bursts, with the garlic naan hero.',
          bz: 'Lake day, naan night. Happy Fourth, Little Elm! Grab pickup on the way home. 🎆 #July4th #LittleElm #LakeLewisville',
          ry: 'Fireworks, then a feast. Happy Fourth of July from Curry District. #July4th #LittleElmTX' },
        story: { action: 'Map-pin frame: “On your way back from the lake?” with an order link.',
          bz: 'Sandy feet welcome. Order ahead for pickup.',
          ry: 'Order ahead and collect on your way home from the lake.' },
        gbp: { action: 'Update post, plus holiday hours for Jul 4.',
          bz: 'Fourth of July in Little Elm? Order Curry District trays for the backyard party: biryani, tandoori and plenty of naan. Pickup or delivery.',
          ry: 'Celebrate the Fourth with Curry District catering in Little Elm. Check our holiday hours and order ahead.' },
        store: { action: '“Feast Season” sticker on lake-weekend tray orders.',
          bz: 'Lake day, naan night.',
          ry: 'Happy Fourth.' }
      },
      kpi: 'Pickup orders Jul 2 to 5, plus link taps on the story.',
      notes: ['Holiday hours are unverified. Confirm them.', 'Fireworks drawn as rangoli-style bursts, so no flags are needed.']
    },
    {
      id: 'back-to-school', month: '2027-08', name: 'Back-to-school lunch boxes', short: 'Back to school',
      cat: 'us', catering: true, approx: true, dateKind: 'month',
      dateLabel: 'Mid-August 2027', dateShort: 'mid-Aug', dateNote: 'Check the Little Elm, Frisco and Prosper ISD calendars. Month-level only.',
      ics: { start: '2027-08-01', marker: true, alarm: 0 }, icon: 'tiffin', post: null, kit: 'topper',
      about: 'Little Elm, Frisco and Prosper schools return in August; parents and staff need easy lunches.',
      concept: 'Lunch, boxed and sorted: lunch-box orders for parents, plus trays for teacher meetings and PTA nights.',
      lead: 'Push the week before school starts',
      channels: {
        ig: { action: 'Tiffin-stripes carousel: “Lunch, boxed”.',
          bz: 'Lunch, boxed and sorted. Back-to-school week just got easier. #BackToSchool #LittleElm #DFWEats',
          ry: 'Lunch, neatly boxed. A calm start to the school year. #BackToSchool #LittleElmTX' },
        story: { action: 'Teacher shout-out question box; reshare with permission.',
          bz: 'Shout out a teacher who makes it all happen.',
          ry: 'Tell us about a teacher who made a difference.' },
        gbp: { action: 'Update post with an Order online button (lunch-box contents still to confirm).',
          bz: 'Back to school in Little Elm: order Curry District lunch boxes for pickup, or call about trays for staff meetings and PTA events.',
          ry: 'Curry District in Little Elm offers lunch boxes and staff-meeting trays for the new school year. Call to plan.' },
        store: { action: 'Tiffin-stripe band on lunch-box lids (from the packaging kit).',
          bz: 'Lunch, boxed and sorted.',
          ry: 'Lunch, neatly boxed.' }
      },
      kpi: 'Weekday lunch orders in the first 3 school weeks, plus PTA and teacher-tray enquiries.',
      notes: ['The contents of the “Lunch Box” menu section are unverified. Confirm them before promoting it.', 'No school logos. PTA tie-ins come from research (spirit nights, teacher trays).']
    },
    {
      id: 'raksha-bandhan', month: '2027-08', name: 'Raksha Bandhan', short: 'Raksha Bandhan',
      cat: 'indian', catering: false, approx: true, dateKind: 'month',
      dateLabel: 'August 2027', dateShort: 'Aug', dateNote: APPROX + '.',
      ics: { start: '2027-08-01', marker: true, alarm: 0 }, icon: 'ribbon', post: null, kit: 'topper',
      about: 'A celebration of brothers and sisters (and cousins), often with sweets and a family meal.',
      concept: 'Sibling dinner, sorted: a “tag your sibling” social push and a nudge toward Sweet Street.',
      lead: 'Post 3 days out',
      channels: {
        ig: { action: 'Carousel of sibling “order personalities” (food and family only).',
          bz: 'Tag the sibling who always steals your naan. Happy Raksha Bandhan! #RakshaBandhan #LittleElm',
          ry: 'Happy Raksha Bandhan. Here’s to siblings, and to sharing the last bite. #RakshaBandhan #LittleElmTX' },
        story: { action: '“Your sibling’s order” this-or-that polls.',
          bz: 'Your sibling’s order: Butter Chicken or Chilli Paneer?',
          ry: 'Celebrating siblings this weekend? Plan your table with us.' },
        gbp: { action: 'Update post with a dessert photo (confirm the menu first).',
          bz: 'Happy Raksha Bandhan from Curry District, Little Elm! Bring your siblings for dinner and save room for Sweet Street.',
          ry: 'Celebrate Raksha Bandhan with family at Curry District in Little Elm: plates for sharing and a sweet finish.' },
        store: { action: 'Festival bag topper on dessert and family orders.',
          bz: 'Share the last bite. (Or don’t.)',
          ry: 'For siblings, with love.' }
      },
      kpi: 'Tagged-sibling comments, plus how often orders that weekend include dessert.',
      notes: ['Keep the imagery to food and family. Avoid ritual close-ups.']
    },
    {
      id: 'india-independence', month: '2027-08', name: 'India’s Independence Day', short: 'India Independence Day',
      cat: 'indian', catering: false, approx: false, dateKind: 'fixed',
      dateLabel: 'Sun Aug 15, 2027', dateShort: 'Aug 15', dateNote: 'Fixed date.',
      ics: { start: '2027-08-15', alarm: 7 }, icon: 'kite', post: null, kit: null,
      about: 'India’s national day, marked across the diaspora with gatherings, music and (in some cities) kite flying.',
      concept: 'A respectful, text-led greeting with kite motifs. No flag on food or packaging.',
      lead: 'Greeting on the day',
      channels: {
        ig: { action: 'Text-led greeting with kite motifs and no flag graphics.',
          bz: 'Happy Independence Day to everyone celebrating India’s big day, from all of us on FM 423. #IndiaIndependenceDay #LittleElm',
          ry: 'Warm wishes on India’s Independence Day from all of us at Curry District. #IndiaIndependenceDay #LittleElmTX' },
        story: { action: 'One greeting frame, plus a repost of a community event (with permission).',
          bz: 'Happy Independence Day, India!',
          ry: 'Wishing everyone a joyful Independence Day.' },
        gbp: { action: 'Optional Update post linking to local community events.',
          bz: 'Happy Independence Day to our Indian-American neighbors in Little Elm and Frisco, from Curry District.',
          ry: 'Warm Independence Day wishes to our Indian-American neighbors, from all of us at Curry District, Little Elm.' },
        store: { action: 'Counter greeting card only.',
          bz: 'Happy Independence Day!',
          ry: 'Happy Independence Day.' }
      },
      kpi: 'Shares from community accounts, plus leads for event partnerships.',
      notes: ['India’s flag code discourages printing the flag on food packaging, napkins or disposables, so keep it text-led.', 'Check local Independence Day events in Frisco and Plano for catering tie-ins.']
    },
    {
      id: 'ganesh-season', month: '2027-09', name: 'Ganesh Chaturthi season', short: 'Ganesh Chaturthi',
      cat: 'indian', catering: true, approx: true, dateKind: 'month',
      dateLabel: 'Late Aug – September 2027', dateShort: 'Sep', dateNote: APPROX + '.',
      ics: { start: '2027-09-01', marker: true, alarm: 0 }, icon: 'marigold', post: null, kit: 'topper',
      about: 'A major festival season for many Indian families, with home and community gatherings over several days.',
      concept: 'Community-gathering trays, offered quietly: a text-led greeting, plus a catering note for organizers.',
      lead: 'Organizer outreach 3 weeks out',
      channels: {
        ig: { action: 'Text-led greeting on the marigold pattern. No deity imagery.',
          bz: 'Warm wishes to everyone celebrating Ganesh Chaturthi this season, from all of us at Curry District.',
          ry: 'Warm wishes to all who celebrate Ganesh Chaturthi, from everyone at Curry District, Little Elm.' },
        story: { action: 'One greeting frame.',
          bz: 'Warm festival wishes, Little Elm!',
          ry: 'Warm wishes for the festival season.' },
        gbp: { action: 'Update post: catering for community gatherings.',
          bz: 'Organizing a community gathering this festival season? Curry District in Little Elm caters trays of vegetarian dishes and more. Call to plan.',
          ry: 'Planning a community gathering? Curry District in Little Elm caters vegetarian and non-vegetarian trays. Please call to discuss your menu.' },
        store: { action: 'Festival bag topper on catering orders.',
          bz: 'Warm festival wishes!',
          ry: 'With warm wishes.' }
      },
      kpi: 'Enquiries from community organizers, plus repeat orders.',
      notes: ['No deity imagery or sacred symbols in any asset.', 'Many gatherings are vegetarian-only. Never claim a vegetarian-only kitchen unless confirmed.', 'Have community members review before publishing.']
    },
    {
      id: 'football-fridays', month: '2027-09', name: 'Friday-night football', short: 'Friday-night football',
      cat: 'us', catering: true, approx: true, dateKind: 'month',
      dateLabel: 'Fridays, late Aug – Nov 2027', dateShort: 'Fridays', dateNote: 'Season dates: check the ISD schedule. It’s also on right now (Oct–Nov 2026).',
      ics: { start: '2027-09-03', rrule: 'FREQ=WEEKLY;BYDAY=FR;COUNT=12', alarm: 0 }, icon: 'stadium', post: 'football-fridays', kit: 'sticker-game',
      about: 'Texas high-school football: on Friday nights the whole town turns out.',
      concept: 'Friday night bites: post-game pickup for families and team-dinner trays for booster clubs.',
      lead: 'Every Friday of the season',
      channels: {
        ig: { action: 'Stadium-lights post, plus a weekly story reminder.',
          bz: 'Friday night bites. Win or lose, the naan’s on its way. #TexasFootball #LittleElm #DFWEats',
          ry: 'Friday nights, well fed. Post-game pickup and team-dinner trays for the home crowd. #TexasFootball #LittleElmTX' },
        story: { action: 'Every Friday: a “post-game pickup” frame with a countdown.',
          bz: 'Post-game hunger is real. Order ahead.',
          ry: 'Order ahead for an easy post-game dinner.' },
        gbp: { action: 'Weekly Update post during the season.',
          bz: 'Friday football in Little Elm? Order Curry District for an easy post-game dinner, or call about team-dinner trays for boosters.',
          ry: 'Feeding the team? Curry District in Little Elm caters team dinners and booster events. Call to plan.' },
        store: { action: '“Game Day” sticker on Friday orders; flyer for booster clubs.',
          bz: 'Game day, District style.',
          ry: 'Game day, well fed.' }
      },
      kpi: 'Friday-night pickup orders against other weeknights, plus tray orders from booster clubs.',
      notes: ['School names, mascots and logos are off-limits without permission.', 'The season is on now, so this can start in Oct 2026.']
    }
  ];

  /* The 12 Instagram posts (each rendered in both directions). Lines are Bazaar headline lines (Bowlby, uppercase). */
  var POSTS = [
    { id: 'navratri-dussehra', dish: 'paneer-tikka', motif: 'dussehra',
      bz: { bg: '#FFB000', fg: '#1D1147', accent: '#E4147E', disc: '#FFF4DC', ray: '#FFC740', logo: 'mono-indigo', kicker: 'Dussehra', lines: ['Happy', 'Dussehra!'], sub: 'Garlands up, plates full. Warm wishes from all of us on FM 423.', cta: 'Plan a garba-night tray' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#C21D4C 0%,#A3173F 40%,#5E0E2A 100%)', pat: '04-marigold-damask-ruby', kicker: 'Dussehra · Festival season', head: 'Happy <em>Dussehra</em>', sub: 'Marigolds at the door, a generous table inside.' } },
    { id: 'diwali', dish: 'gulab-jamun', motif: 'diwali',
      bz: { bg: '#1D1147', fg: '#FFF4DC', accent: '#FFB000', disc: '#E4147E', ray: '#2A1A5E', logo: 'reversed', kicker: 'Diwali', lines: ['Lights on.', 'Sweets out.'], sub: 'Hosting Diwali? Let us handle the platters while you handle the lights.', cta: 'Call to plan' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 28%,#3A1B52 0%,#231034 45%,#160B26 100%)', pat: '01-jali-lattice-midnight', kicker: 'Diwali · Festival of Lights', head: 'Lights up, plates <em>full</em>.', sub: 'Planning a Diwali gathering? Call us to plan your catering.' } },
    { id: 'thanksgiving', dish: 'tandoori-platter', motif: 'thanksgiving',
      bz: { bg: '#FF6A13', fg: '#1D1147', accent: '#FFF4DC', disc: '#FFB000', ray: '#FF7F33', logo: 'mono-indigo', kicker: 'Friendsgiving', lines: ['Pass the', 'naan.'], sub: 'Thanksgiving and Friendsgiving trays from the Tandoor Quarter.', cta: 'Call to plan' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#6A2A6E 0%,#4B1D52 45%,#24102E 100%)', pat: '07-spice-botanical-midnight', kicker: 'Thanksgiving', head: 'Gratefully <em>shared</em>.', sub: 'Thanksgiving catering from Curry District, planned with you.' } },
    { id: 'holiday-trays', dish: 'biryani', motif: 'holiday',
      bz: { bg: '#00A8A0', fg: '#1D1147', accent: '#FFF4DC', disc: '#FFF4DC', ray: '#14B5AD', logo: 'mono-indigo', kicker: 'Holidays & NYE', lines: ['Party trays,', 'sorted.'], sub: 'Office party? New Year’s Eve crew? Bring the guest list.', cta: 'Call to plan' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#17705C 0%,#0F4D3F 45%,#082A23 100%)', pat: '06-star-tile-emerald', kicker: 'Holidays & New Year’s Eve', head: 'Hosting, made <em>gracious</em>.', sub: 'Holiday and New Year’s Eve trays. Call us to plan.' } },
    { id: 'sankranti-pongal', dish: 'mango-lassi-chai', motif: 'kites',
      bz: { bg: '#FFE7B8', fg: '#1D1147', accent: '#FF6A13', disc: '#00A8A0', ray: '#FFDDA0', logo: 'full-colour', kicker: 'Sankranti & Pongal', lines: ['Kites up.', 'Chai out.'], sub: 'Happy Makar Sankranti and Pongal, Little Elm!', cta: 'Chai’s on the stove' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 26%,#1C96A0 0%,#117C86 40%,#0A3F45 100%)', pat: '05-peacock-eye-peacock', kicker: 'Makar Sankranti & Pongal', head: 'A harvest of <em>wishes</em>.', sub: 'Happy Makar Sankranti and Pongal from our kitchen to your home.' } },
    { id: 'valentines', dish: 'butter-chicken', motif: 'valentines',
      bz: { bg: '#E4147E', fg: '#FFF4DC', accent: '#FFB000', disc: '#FFF4DC', ray: '#EC2C8C', logo: 'mono-cream', kicker: 'Valentine’s', lines: ['Love at', 'first dip.'], sub: 'Two plates, one shared garlic naan. Happy Valentine’s!', cta: 'Date night, sorted' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#7A1239 0%,#4A0E2A 45%,#160B26 100%)', pat: '03-paisley-vine-ruby', kicker: 'Valentine’s · Date night', head: 'Dinner, made an <em>occasion</em>.', sub: 'Two plates, one shared garlic naan and nowhere else to be.' } },
    { id: 'eid', dish: null, motif: 'eid',
      bz: { bg: '#1D1147', fg: '#FFF4DC', accent: '#FFB000', disc: '#00A8A0', ray: '#24165A', logo: 'reversed', kicker: 'Warm wishes', lines: ['Eid', 'Mubarak'], sub: 'Warm wishes to everyone celebrating, from all of us at Curry District.', cta: null },
      ry: { bg: 'radial-gradient(120% 90% at 50% 34%,#17705C 0%,#0F4D3F 48%,#072620 100%)', pat: '06-star-tile-emerald', kicker: 'With warm wishes', head: 'Eid <em>Mubarak</em>', sub: 'Warm wishes to you and your loved ones from all of us at Curry District.' } },
    { id: 'holi', dish: 'samosa-chutney', motif: 'holi',
      bz: { bg: '#FFF4DC', fg: '#1D1147', accent: '#E4147E', disc: '#FFB000', ray: '#FFEBC4', logo: 'full-colour', kicker: 'Holi', lines: ['Color me', 'hungry.'], sub: 'Happy Holi, Little Elm! Snacks for the after-party are on FM 423.', cta: 'Order pickup' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#FFFBF2 0%,#FBF3E4 50%,#F1E2C6 100%)', pat: '03-paisley-vine-ivory', light: true, kicker: 'Holi · Festival of colors', head: 'Happy <em>Holi</em>', sub: 'Bright colors outside, bright flavors at the table.' } },
    { id: 'ugadi', dish: 'thali', motif: 'ugadi',
      bz: { bg: '#3FA34D', fg: '#1D1147', accent: '#FFF4DC', disc: '#FFF4DC', ray: '#4CB05A', logo: 'mono-indigo', kicker: 'Ugadi', lines: ['New year,', 'new heat.'], sub: 'Happy Ugadi! Andhra-style fire, right here on FM 423.', cta: 'Pick your heat' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#14695A 0%,#0F4D3F 45%,#0A2E33 100%)', pat: '07-spice-botanical-emerald', kicker: 'Ugadi · Telugu New Year', head: 'Happy <em>Ugadi</em>', sub: 'A new year at the table, with Andhra-style fire and a little sweetness.' } },
    { id: 'mothers-day', dish: 'dal-saag', motif: 'mothers',
      bz: { bg: '#FFF4DC', fg: '#1D1147', accent: '#E4147E', disc: '#E4147E', ray: '#FFE9C2', logo: 'full-colour', kicker: 'Mother’s Day', lines: ['Mom’s', 'night off.'], sub: 'We’ll cook. You bring Mom. Tag the mom who fed everyone.', cta: 'Bring the family' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 30%,#FFF6EC 0%,#F9E5D9 50%,#F0CDBE 100%)', pat: '04-marigold-damask-ivory', light: true, kicker: 'Mother’s Day', head: 'Tonight, Mom is our <em>guest</em>.', sub: 'Mother’s Day at Curry District, Little Elm.' } },
    { id: 'july-4', dish: 'garlic-naan', motif: 'july4',
      bz: { bg: '#3A1B7A', fg: '#FFF4DC', accent: '#FFB000', disc: '#00A8A0', ray: '#43228A', logo: 'reversed', kicker: 'Fourth of July', lines: ['Lake day,', 'naan night.'], sub: 'Happy Fourth, Little Elm! Grab pickup on the way home.', cta: 'Order pickup' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 26%,#14646E 0%,#0E3F4E 40%,#160B26 100%)', pat: '08-brass-dots-diamonds-midnight', kicker: 'Fourth of July', head: 'Fireworks, then a <em>feast</em>.', sub: 'Happy Fourth of July. Order ahead for the lake crowd.' } },
    { id: 'football-fridays', dish: 'chilli-chicken', motif: 'football',
      bz: { bg: '#D62839', fg: '#FFF4DC', accent: '#FFB000', disc: '#1D1147', ray: '#DE3646', logo: 'mono-cream', kicker: 'Friday-night football', lines: ['Friday', 'night bites.'], sub: 'Post-game pickup and team-dinner trays for the home crowd.', cta: 'Order ahead' },
      ry: { bg: 'radial-gradient(120% 90% at 50% 26%,#3B1A4A 0%,#24102E 45%,#160B26 100%)', pat: '02-mehrab-trellis-midnight', kicker: 'Friday-night football', head: 'Friday nights, well <em>fed</em>.', sub: 'Post-game pickup and team-dinner trays for the home crowd.' } }
  ];

  var KIT = {
    'sticker-lights': { title: 'Festival of Lights sticker', use: 'Diwali: every bag for 3 weeks' },
    'sticker-feast': { title: 'Feast Season sticker', use: 'Thanksgiving to New Year, grad and lake-day trays' },
    'sticker-color': { title: 'Color Season sticker', use: 'Holi week' },
    'sticker-game': { title: 'Game Day sticker', use: 'Football Fridays, cricket nights, the big game' },
    'topper': { title: 'Festival bag topper', use: 'Catering orders for any celebration (write the greeting in)' }
  };

  var DATA = { months: MONTHS, moments: MOMENTS, posts: POSTS, kit: KIT, approxText: APPROX, lunarText: LUNAR };
  if (typeof module !== 'undefined' && module.exports) module.exports = DATA; else root.CD_CAL = DATA;
})(this);
